# Generated by Django 2.2.5 on 2019-10-26 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clueless', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cardType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hasSecretPassage', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clueless.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('movedBySuggestion', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hallway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clueless.Board')),
                ('room1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacent_room_one', to='clueless.Room')),
                ('room2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacent_room_two', to='clueless.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('currentPlayer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clueless.Player')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterCard', models.ForeignKey(limit_choices_to={'cardType': 'character'}, on_delete=django.db.models.deletion.CASCADE, related_name='casefile_character_card', to='clueless.Card')),
                ('roomCard', models.ForeignKey(limit_choices_to={'cardType': 'room'}, on_delete=django.db.models.deletion.CASCADE, related_name='casefile_room_card', to='clueless.Card')),
                ('weaponCard', models.ForeignKey(limit_choices_to={'cardType': 'weapon'}, on_delete=django.db.models.deletion.CASCADE, related_name='casefile_weapon_card', to='clueless.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clueless.Player'),
        ),
        migrations.AddField(
            model_name='board',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clueless.Game'),
        ),
    ]
