# Generated by Django 2.2.5 on 2019-10-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0002_auto_20191026_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currentHallway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clueless.Hallway'),
        ),
        migrations.AddField(
            model_name='player',
            name='currentRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clueless.Room'),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_player_is_in', to='clueless.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='currentPlayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_player_turn', to='clueless.Player'),
        ),
    ]
