# Generated by Django 2.2.5 on 2019-10-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0003_auto_20191026_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='character',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
