# Generated by Django 2.2.5 on 2019-10-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0005_auto_20191026_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clueless.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
