# Generated by Django 2.2.5 on 2019-11-02 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0006_auto_20191026_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clueless.Board'),
        ),
    ]
