# Generated by Django 2.2.5 on 2019-11-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0007_auto_20191102_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hasMadeSuggestionInRoom',
            field=models.BooleanField(default=False),
        ),
    ]
