# Generated by Django 2.2.5 on 2019-11-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0008_player_hasmadesuggestioninroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clueless.Game'),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clueless.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clueless.Board'),
        ),
        migrations.AlterField(
            model_name='game',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clueless.CaseFile'),
        ),
    ]
