# Generated by Django 2.2.5 on 2019-11-02 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0009_auto_20191102_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='unplayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
