# Generated by Django 2.2.5 on 2019-11-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0012_notification_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='specialMessage',
            field=models.CharField(default='', max_length=500),
        ),
    ]
