# Generated by Django 2.2.5 on 2019-11-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0013_game_specialmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hasMadeSuggestionThisTurn',
            field=models.BooleanField(default=False),
        ),
    ]
