# Generated by Django 2.2.5 on 2019-11-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0014_player_hasmadesuggestionthisturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hasMovedThisTurn',
            field=models.BooleanField(default=False),
        ),
    ]
