# Generated by Django 2.2.5 on 2019-11-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0015_player_hasmovedthisturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clueless.Board'),
        ),
        migrations.AlterField(
            model_name='game',
            name='currentPlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_player_turn', to='clueless.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clueless.CaseFile'),
        ),
        migrations.AlterField(
            model_name='player',
            name='currentHallway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clueless.Hallway'),
        ),
        migrations.AlterField(
            model_name='player',
            name='currentRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clueless.Room'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_player_is_in', to='clueless.Game'),
        ),
    ]
