# Generated by Django 2.2.5 on 2019-11-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0017_auto_20191111_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='disprovePlayer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
